DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  cost DOUBLE UNSIGNED NOT NULL,
  purchased BOOL NOT NULL
);